---
title: "Derivatives in R"
author: "Felicia Cruz"
date: "8/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(palmerpenguins)
```

### First order univariate derivatives

```{r}
# A
fx <- expression(x^2)
df_dx <- D(expr = fx, 'x') 

x<- 3
df_dx_3 <- eval(expr = df_dx)

df_dx_3
```

```{r}
# B 
pa <- expression(2*(3*a + 2)^4 - 5)
dp_da <- D(expr = pa, 'a')

a <- 1.2
dp_da_1_2 <- eval(expr = dp_da)

dp_da_1_2
```

```{r}
#C 
gt <- expression(-4*t/((t^2+1)^3))
dg_dt <- D(expr = gt, 't')

t <- 0 
dg_dt_0 <- eval(expr = dg_dt)

dg_dt_0
```


### Higher order univariate derivatives

```{r}
gz <- expression(4.6 - 1.9*z^3)
dg_dz <- D(expr = gz, 'z')

dg_dz_2 <- D(expr = dg_dz, 'z')
```

### Partial derivatives 

```{r}

fxyz <- expression(2*x^2*y - 3*x + 1 + 4*z^4*x)

df_dxx <- D(expr = fxyz, 'x')
df_dyy <- D(expr = fxyz, 'y')
df_dzz <- D(expr = fxyz, 'z')

```

## Section 4: Plots 

```{r}
fx_4 <- function(x){
  2.4*(exp(-0.05*x))*sin(x)
}
  

ggplot(data = NULL) +
  stat_function(fun = fx_4) +
  xlim(min = -0.5, max = 0.5)

```

### Penguin Plots 

#### Bill Measurements by Species 
```{r}
ggplot(data = penguins, aes(x = bill_length_mm, y = bill_depth_mm)) +
  geom_point(aes(color = species)) +
  scale_color_manual(values = c("magenta", "blue", "green")) +
  labs(x = "Bill length (mm)", 
       y = "Bill depth (mm)", 
       title = "Palmer Penguin Bill Measurements",
       color = "Species")
```

#### Flipper Length by Species 
```{r}
ggplot(data = penguins, aes(x = species, y = flipper_length_mm)) + 
  geom_jitter(aes(color = species)) + 
  labs(x = "Species",
       y = "Flipper length (mm)",
       title = "Palmer Penguin Flipper Lengths",
       color = "Species")
```

